# Generated by Django 3.0.8 on 2020-07-16 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(blank='true', default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank='true', max_length=10000),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank='true', max_length=10000),
        ),
    ]
