# Generated by Django 3.0.8 on 2020-07-16 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200716_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateTimeField(blank='true', default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
    ]
