# Generated by Django 3.0.8 on 2020-07-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200716_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateTimeField(default='2000-01-01 00:00:00'),
        ),
    ]
