# Generated by Django 3.0.8 on 2020-07-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200716_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateTimeField(default='2000-01-01'),
        ),
    ]
